#
###################################
# Site wide configuration
####################################
#
title: aprilofthisworld
email: aprilofthisworld@gmail.com
description: aprilofthisworld's blog,powered by jekyll.
# the base hostname & protocol for your site
url: https://aprilofthisworld.github.io
keywords: ["Java", "blog", "jekyll"]


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# git talk configuration
####################################
#

gittalk:
  client_id: '6e18630438831e5b3721'
  client_secret: '50ce8fe736e35eaecb6c9ba8d6d86edc0103597b'
  repo: 'aprilofthisworld.github.io'
  owner: 'aprilofthisworld'
  admin: 'aprilofthisworld'
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 无邪
  avatar: leonids-logo.png
  job: "JAVA"
  bio: ""
  email: aprilofthisworld@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  #username
  github: aprilofthisworld
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

data:
  index:
    projects:
      name: java相关
      descr: Java学习相关
      github: https://github.com/aprilofthisworld/aprilofthisworld.github.io
      website: https://github.com/aprilofthisworld/aprilofthisworld.github.io
